namespace Model.Entities.MonolithArena;

public enum RuneType
{
    STRENGTH,
    ACCURACY,
    REINFORCEMENT,
    AGILITY,
    MINOR_ACCELERATION,
    GREATER_ACCELERATION,
    REGENERATION,
    DISARMAMENT,
    DOUBLE_ATTACK,
    TELEPORTATION,
    PENETRATION
}